# Site wide configuration

title: Troy Gilbert
description: "I make games."
logo: logo.png # 120x120 px default image used for Twitter summary card
teaser: teaser-empty.png # 400x250 px default teaser image used in image archive grid
locale:
url: http://troygilbert.com
# url: http://localhost:4000

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Troy Gilbert
  email: troy.gilbert@gmail.com
  twitter: troygilbert
  google:
    ad-client:
    ad-slot:
  bio: I make games.
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: troygilbert


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
